### ISSUE TITLE
Fix base url

### ISSUE THREAD

**Issue by kaitlinnewson** [code4lib/2019.code4lib.org#1]
Currently all of the assets are broken because we're using github.io links.

**Comment by streeetlamp** [comment]
Related Jekyll Docs  
https://jekyllrb.com/docs/github-pages/

**Comment by streeetlamp** [comment]
Believe I have it solved via some template filters and tags. 
For example: 
`{{ "/assets/css/main.css" | relative_url }}`  
`{{ site.baseurl }}{% link speakers/past-keynotes.html %}`  

I could go ahead and submit a PR by end of day tomorrow probably

**Comment by streeetlamp** [comment]
aaand PR as promised  
https://github.com/code4lib/2019.code4lib.org/pull/2
