### ISSUE TITLE
Workshops display should link back to their index

### ISSUE THREAD

**Issue by phette23** [code4lib/2019.code4lib.org#113]
There's no way to go from an individual workshop page to the full list of them at `/workshops/`. I'm not saying we need breadcrumbs everywhere but I've found it a bit troublesome to navigate just as I'm testing the site.

**Comment by phette23** [comment]
No, no one's worked on it yet that I know of. I think I just found the workshops link—if you click the "February 19th" date you go back to the index. That's pretty subtle. I was thinking something like prefixing the titles with "Workshops > ..." or something but I don't have any solid ideas.

**Comment by phette23** [comment]
This issue also applies to posters, too. Just a general issue with the "presentation" layout.

**Comment by streeetlamp** [comment]
PR incoming, here is what we came up with 
![screen shot 2019-01-10 at 2 42 12 pm](https://user-images.githubusercontent.com/1740634/50992728-f14e0800-14e5-11e9-9cf2-f3a96294da81.png)

**Comment by streeetlamp** [comment]
merged so closing
