### ISSUE TITLE
content - new Emergency section

### ISSUE THREAD

**Issue by phette23** [code4lib/2019.code4lib.org#12]
The local Emergency section with information like local hospitals, police, etc. needs to be updated for San Jose. It's present on the Conduct page: https://2019.code4lib.org/conduct/

We just need to research and write this section, no coding required really. See 2018 site for example of the info: https://2018.code4lib.org/conduct/#emergency

**Comment by snarkshow** [comment]
This is my first pass at the emergency info section.  One thing I haven't gotten around to yet is confirming whether the hospital information is accurate.  I thought I might email the venue about that.

https://docs.google.com/document/d/149aBy3e0m3GwcQO_WOwk10oC4T73FLji1H33_K3lzEk/edit?usp=sharing

Someone please tell me if I'm doing this commenting thing right :)

**Comment by snarkshow** [comment]
Updated the emergency care info and confirmed it with the sales dept of the venue

**Comment by kaitlinnewson** [comment]
@snarkshow is this ready to go up on the website?

**Comment by snarkshow** [comment]
Yes!  I was actually going to ask at today's meeting whether it's possible for someone to walk me through publishing something on the website
