### ISSUE TITLE
add conference schedule to the website

### ISSUE THREAD

**Issue by phette23** [code4lib/2019.code4lib.org#125]
- convert program schedule to website YAML data
- switch main menu link to go to /schedule/ not /schedule/timeline

**Comment by arosebrewer** [comment]
I am working on this, just had some technical hiccups yesterday (and a nasty bike accident.) Expecting to make progress today.

**Comment by kaitlinnewson** [comment]
Oh no, hope everything is okay! Let us know if you need to pass this on to someone else.

**Comment by phette23** [comment]
I hope you're alright! Let me know if you need help, I have some time today. As far as I can tell, there's no easier way to make the schedule data than just looking at the spreadsheet and turning it into data that mimics last year's file - https://github.com/code4lib/2018.code4lib.org/blob/master/_data/schedule.yml

**Comment by arosebrewer** [comment]
Thanks all! I appreciate it. I'm on it, though, and should be finished soon!
