### ISSUE TITLE
add reception information

### ISSUE THREAD

**Issue by phette23** [code4lib/2019.code4lib.org#140]
See last year's LoC reception for an example.

- location: The Tech Museum https://www.thetech.org/
- date: wednesday (day one)

activate the reception display in conf.yml, uncomment the menu item in /general-info/venues/index, check that the block shows up under the correct day on /schedule/index.html, fill in details in general-info/venues/reception.html, add an image of the place.

**Comment by kaitlinnewson** [comment]
Are there more details available, or is this just what we have at the moment? E.g. will refreshments be served like last year, any security info, specific exhibits that will be open, etc.

**Comment by phette23** [comment]
Huh we don't really have that extra info yet. There will be refreshments but I'm not sure about security, exhibits. I'll ask at the next LPC.

**Comment by phette23** [comment]
We don't really have additional details and won't for some time so I think it's OK to close this for now. I'll reopen if there are additional details to be added.
