### ISSUE TITLE
add speaker photo

### ISSUE THREAD

**Issue by kimpham54** [code4lib/2019.code4lib.org#142]
Hello! Can we add a photo for jeremy nelson? https://2019.code4lib.org/workshops/LD4Ps-Sinopia-Linked-Data-Editing-Environment
![20180708_122954](https://user-images.githubusercontent.com/2915770/49540292-f091d880-f88c-11e8-98d3-41b3771a49d0.jpg)

**Comment by phette23** [comment]
Thanks @kimpham54 I sent in a PR addressing this and #141 just now
