### ISSUE TITLE
Community Support Volunteers/Community Support Squad - Feb. 12th

### ISSUE THREAD

**Issue by kayiwa** [code4lib/2019.code4lib.org#157]
Thank you for adding the following names to the Duty Officers (we hope the community will retire this name for Code4lib 2020) Page

Karen Coyle
Justin Coyne
Shaun Ellis
Erin Fahy
Bobbi Fox
Wayne Graham
Francis Kayiwa
Megan Kudzia
Hardy Pottinger
Anne Slaughter

Do let me know what you need from of us. Either collectively or individually.

**Comment by kaitlinnewson** [comment]
Thanks @kayiwa. Are there images for the duty officers? This is what the page looked like last year: https://2018.code4lib.org/conduct/#officers 

Once a schedule is available for duty officers, let us know and we'll get that up too.

**Comment by kayiwa** [comment]
@arosebrewer one of the officers already has an image. https://2019.code4lib.org/workshops/Wait-what-Getting-your-bearings-with-ServerSpec

**Comment by bibliotechy** [comment]
My photo is available from last years site - https://github.com/code4lib/2018.code4lib.org/blob/master/assets/img/duty-officers/Nelson_Chad.jpg

**Comment by arosebrewer** [comment]
Looked through speaker and duty officer photos from last year, and speaker photos from this year to look for some of these photos. I didn't go further back than 2018 for the sake of having decently updated photos, but I could. The below names *without* an x next to them are photos I **still need**

Karen Coyle
Justin Coyne
Erin Fahy
Wayne Graham
Megan Kudzia
Anne Slaughter

Any contact information for the above names would be much appreciated, and I'll reach out to get a photo!

These names below, with an x, are photos I **have**.

x Shaun Ellis
x Bobbi Fox
x Francis Kayiwa
x Hardy Pottinger
x Chad Nelson

**Comment by kayiwa** [comment]
heya. My apologies. I've pinged those missing pictures. While I have your attention, thank you in advance for removing Hardy Pottinger from this list.

**Comment by kayiwa** [comment]
Anne Slaughter here. https://drive.google.com/file/d/1La-dGYYUCmMJUXFKX50_xSe-uracHp1f/view?usp=sharing

**Comment by waynegraham** [comment]
Wayne Graham: https://www.clir.org/wp-content/uploads/sites/6/2016/11/wayne-e1479223058856.jpg

**Comment by phette23** [comment]
Megan Kudzia - https://2016.code4lib.org/img/speakers/kudzia.jpg

I think using an older image while we wait for speakers to (optionally) send in more current ones. I couldn't find code4lib photos for any of the other people on the list.

**Comment by phette23** [comment]
@ranti found Karen Coyle's PR photos on her personal site: https://www.kcoyle.net/photos.html

so using the 2017 one is probably OK.

**Comment by kaitlinnewson** [comment]
@kayiwa We still need photos for @jcoyne and Erin Fahy - any luck with these?

**Comment by kayiwa** [comment]
heya @kaitlinnewson Please use these dunno if the resolution is good enough. This for Erin. https://github.com/eefahy?tab=followers and  https://avatars0.githubusercontent.com/u/92044?s=400&v=4 for @jcoyne

**Comment by arosebrewer** [comment]
Thanks all for the help rounding up these photos!
