### ISSUE TITLE
fix colours for sponsorship prospectus

### ISSUE THREAD

**Issue by kaitlinnewson** [code4lib/2019.code4lib.org#16]
The current colour scheme is making the prospectus text unreadable: https://2019.code4lib.org/prospectus/ 

We'll also need to improve the contrast in the childcare section.

**Comment by phette23** [comment]
I know this is closed but I did talk about in our last meeting that [I added](https://github.com/code4lib/2019.code4lib.org/blob/d1dcc84902fb646300be28a060a3f3bae195bd45/assets/_scss/_color-contrast.scss) a `color-contrast` SASS function which takes a background color & returns an accessible font color. It's only being used in one place but is handy if more clashes like this exact issue come up.
