### ISSUE TITLE
Hide empty sponsor categories

### ISSUE THREAD

**Issue by kaitlinnewson** [code4lib/2019.code4lib.org#161]
As discussed at today's meeting, we want to hide any categories for sponsors that are empty on https://2019.code4lib.org/sponsors/.

**Comment by snarkshow** [comment]
As with Adamantium, the Diamond category is currently commented out.  

I've spent the last couple of weeks going over the Liquid syntax and docs and... I think I'm officially at the point of spinning my wheels.  These are my notes and questions so far.  I won't be at today's meeting as I've just arrived in Hong Kong and it will be 3 AM by that time, but I've condensed my notes into something (hopefully) legible here:

https://docs.google.com/document/d/1u3jHLy4e0TbOZM1sYNsVQjFTTJpzREGapHQpXpV7TuI/edit?usp=sharing

**Comment by snarkshow** [comment]
I think I cracked it!

**Comment by kaitlinnewson** [comment]
Looks good! Closing this issue.
