### ISSUE TITLE
add Ashley Blewer to preconference workshop

### ISSUE THREAD

**Issue by kimpham54** [code4lib/2019.code4lib.org#163]
Add Ashley Blewer as an instructor to https://2019.code4lib.org/workshops/Forensic-Files-Episode-1-Fishing-for-the-Truth
Use same author link as https://2019.code4lib.org/workshops/Forensic-Files-Episode-2-A-Purr-fect-Match

Thanks!

**Comment by phette23** [comment]
Easy. Thanks @kimpham54 !
