### ISSUE TITLE
Add fourth speaker to preconference session ISLE

### ISSUE THREAD

**Issue by KHaley** [code4lib/2019.code4lib.org#175]
Please add a fourth speaker to the preconference session: ISLE: Islandora for All. The added speaker is: Carolyn Moritz

She will need to be added to the speakers page as well. Her name plus affiliation should read: Carolyn Moritz, Vassar College

Her picture (moritz_carolyn.jpg) is in the presenter photos folder in the Preconference Google Drive. https://drive.google.com/open?id=1GEBfONC64vjljU-TrW5Gg-RkwO93WAIS

**Comment by phette23** [comment]
@KHaley do you have her position at Vassar and a short bio as well? Not required but we can add that info if it's available. I'll send a PR with these changes once I hear back.

**Comment by KHaley** [comment]
Carolyn's position at Vassar is Digital Technologies Librarian.

As far as I know, we didn't ask any of the preconference presenters for
bios.

Kathleen
