### ISSUE TITLE
Combine some Social Activities underneath Gen Info somewhere

### ISSUE THREAD

**Issue by phette23** [code4lib/2019.code4lib.org#192]
The "venues" submenu has grown quite long due to all the Social Activities underneath it:

- Conference Hotel
- Reception
- Accommodations
- Newcomer Dinner
- Game Night
- Karaoke Night
- Build your own event

These are very short sections and I agree with @ranti that combining them into a "social activities" section might be desirable. One limitation is that we need "dinner" to be a standalone section because it's already linked to in the email to registrants that went out today, so we if move it that link will break. But the newcomers dinner is such a major thing to draw attention to I like the idea of leaving it separate. I guess I have two separate ideas and I'm not sure which is better:

- General Info > Venues > Social Activities > headings for game night, karaoke, BYO event
- Gen Info > Social Activities > submenu for game night, karaoke, BYO event

It's worth thinking about which arrangement makes sense for other years, too. This year, a lot more is happening in the hotel, so there's less need to stack things under venue and less details for each item. Other years, these might all happen in disparate places.

**Comment by ranti** [comment]
I'm leaning toward the second option (Gen Info > Social Activities) so the sub-nav would be simpler and the activities easier to find. This arrangement should work regardless the location of the activities. 

For the dinner, we could leave it just the way it is for this year and just link to it.

**Comment by kaitlinnewson** [comment]
Adding this to our "lessons learned" doc for next year and closing.
