### ISSUE TITLE
Game Night incorrect info on main schedule page

### ISSUE THREAD

**Issue by yo-bj** [code4lib/2019.code4lib.org#202]
Hi folks,

On https://2019.code4lib.org/schedule/ Game Night is Listed under Wednesday, when it should be listed under Thursday. In addition, there are a couple other changes:

- the hours need to be changed to 6:30 pm to 9:30 pm
- the description is from 2018's Game Night entry. You can use the text at https://wiki.code4lib.org/2019_Social_Activities#Game_Night.2C_Thursday.2C_February_21st for a replacement.

**Comment by ranti** [comment]
Fixed. Sorry about that and thanks for checking.
