### ISSUE TITLE
menu information

### ISSUE THREAD

**Issue by phette23** [code4lib/2019.code4lib.org#211]
Concentra is going to pass along menu information from the caterers soon (probably this afternoon) which we then need to load into data files on the website and set to display.

**Comment by phette23** [comment]
Here's the data: https://docs.google.com/document/d/1HQrqzcxP93BcY6fPrwF7MvcbYBWmMRnCpzTQTEt6oS4/edit

**Comment by phette23** [comment]
We are still missing allergen notations but we can at least partially add the data now and activate the menu displays so people can see.

**Comment by kaitlinnewson** [comment]
@phette23  will there be menu info for breaks/reception as well? I see we had these last year.

**Comment by phette23** [comment]
Response I got:

> there will be coffee / decaf / asst teas for all AM breaks and Tue PM break. On Wednesday PM break there will also be Tres leches bites. On Thurs PM break there will also be Mini Seasonal Fruit Tartlets.

**Comment by kaitlinnewson** [comment]
Think we can close this @phette23 or are we waiting on more info?

**Comment by phette23** [comment]
I think we should add those break menus (or rather, the Wed/Thu ones at least since it's a little late for today) and I'm going to ask about the Reception right now.

**Comment by kaitlinnewson** [comment]
Okay, I'll add those break menus now.
