### ISSUE TITLE
Add libtechwomen meeting to website

### ISSUE THREAD

**Issue by kaitlinnewson** [code4lib/2019.code4lib.org#215]
From the wiki:

#LibTechWomen Meet-Up, Thursday, February 21st

    When: Thursday, 2/21/19, 5:30 pm to 7:30 pm
    Where: 2050 Lobby Bar, located in Conference Hotel
    Food and beverages are available for purchase
    Afterwards some of us will go to Game Night or Karaoke!

LibTechWomen is a supportive space for women and their friends to network, develop skills, build confidence, and lead positive change. Are you a lurker? Are you a newcomer? All are welcome! Come meet wonderful colleagues in library technology!

**Comment by kaitlinnewson** [comment]
- add to schedule
- add to first timers guide
- add under venues section

**Comment by phette23** [comment]
@snarkshow I only added LibTech Women to the "Schedule" page, did you want to add it under General Info > Venues? I don't think we necessarily _have_ to but it couldn't hurt.

**Comment by snarkshow** [comment]
I've currently added it under General Info > Venues just for consistency's sake.  Right now it's above Game Night and Karaoke because it ends earliest out of all three events but I'm not married to that.
