### ISSUE TITLE
wiki page on how to submit data

### ISSUE THREAD

**Issue by phette23** [code4lib/2019.code4lib.org#25]
see https://github.com/code4lib/2019.code4lib.org/wiki/Best-Practices-for-passing-data-to-the-Website-Working-Group

Looking for feedback from the group. Document goals:

- it's clear & understandable especially to people who a) are new to the Code4Lib conference structure, b) are unfamiliar with Jekyll & the conference site specifically
- it's fairly short (not much longer than the first draft)
- it contains concrete examples & links to relevant places
- it places a reasonable burden on other conference committees to deliver usable data to us in a timely manner

**Comment by kaitlinnewson** [comment]
It may also be useful to note the conference-website Slack channel as another communication channel. Otherwise, looks great to me!

**Comment by streeetlamp** [comment]
excellent imo

**Comment by ranti** [comment]
Looks good. So, we want all speaker images and logos in JPEG format? Based on my experiences, some companies provides logos in GIF only (sometimes PNG as well.)

**Comment by phette23** [comment]
No the file types don't have to JPG, I edited the examples and added a sentence about that. I think we don't really care about type right? We've done all the normal ones in the past.

**Comment by phette23** [comment]
GitHub markdown doesn't allow `slack://` URLs :(

Otherwise the page is done. I'll make sure Program and Sponsorship see this before we start getting too much data sent to us.
