### ISSUE TITLE
Add first timer's guide to site

### ISSUE THREAD

**Issue by kaitlinnewson** [code4lib/2019.code4lib.org#42]
As discussed at today's meeting, let's add the first timer's guide sent out in emails to registrants to the website. Depending on the length, it could either be included on the 'attend' page, or as a sub-page.

Here's the email from last year (with apologies for the formatting):

 ---

We're in the last
 few days before #c4l18 begins, and for a good number of you, this will be your first code4lib. Here is some information to help you navigate through the conference whirlwind next week:
- Schedule: We have
 a packed program with talks, preconferences, lightning talks, & breakout sessions. The full conference & pre-conference schedules are available on the main conference page [1]. The venue will provide lunch Wednesday and Thursday, as well as morning and afternoon
 break snacks Wednesday through Friday morning. Menus will be posted on the website soon.  There will be caffeine.
- Social Activities
 [2]: There's a lot going on outside of the sessions, and this page has information about various gatherings, events, meals, etc. In addition, if you have any events that you’d like to organize, please feel free to add the event to the DIY Event Google Doc
 [3]! 
One activity I want
 to highlight is the Newcomer dinner [4] on Tuesday, February 13th. There are still a lot of great restaurants left on the list, and this is your chance to meet folks you might otherwise not get a chance to talk to at the conference. Read the guidelines and
 pick your restaurant (c4l veterans - this means you too!). 
Another event is
 Game Night on Wednesday, February 14th. While you do not need to bring something to participate, please let us know if you do plan to bring games [5].  Most importantly, bring yourself!
Lastly, since this
 year’s conference falls on Ash Wednesday, the Social Activities Crew is compiling a list of Ash Wednesday services near the hotel [6].
- Volunteering: A
 round of applause for everyone who has helped to plan the conference! So much of what goes into making this event possible each year happens through the tireless efforts of our community members.  The work isn't *quite* done yet, and we're still looking for
 volunteers for a few on-site tasks [7] - the Whatever Crew is always looking for more
red shirts
 volunteers! 
- IRC/Twitter/Slack.:
 Use the #c4l18 hashtag for conference related tweets, posts, pictures, and so on. The IRC channel [8] is #code4lib, and there will be volunteers at the conference who would be more than happy to help you with IRC. We also have a Slack [9] that volunteers can
 help you get set up at the conference. All channels are very active during the conference so check these channels often for announcements, information, etc.
- For my last item,
 give the following a read: 
-- CodeofConduct4lib
 [10] 
-- Related - Duty
 Officer information for the conference [11] 
If nothing else -
 if you have a question, ask! Ask the conference volunteers, folks who look like they know what they’re doing, folks who *don’t exactly* look like they know what they’re doing, the Slack channel, the Twitter/IRC streams - the choices are plentiful.
Thanks and see you
 next week,
Becky, on behalf
 of the (slow but steady) Welcome Wagon
b.yoose@gmail.com
[1]
http://2018.code4lib.org/schedule/
  
[2]
http://wiki.code4lib.org/2018_Social_Activities
[3]
https://docs.google.com/document/d/1rwbYzsc70HWMZQlUfXJ9Z8YJ476CDY4FZI0zsW9aeBw/edit?usp=sharing
    
[4]
http://2018.code4lib.org/general-info/venues/#dinner
[5]
http://2018.code4lib.org/general-info/venues/#gaming
[6 ]
https://wiki.code4lib.org/2018_Social_Activities#Ash_Wednesday_Services
[7]
http://wiki.code4lib.org/2018_Conference_Volunteers
  
[8]
http://code4lib.org/irc
[9]
https://docs.google.com/forms/d/120Dw1JjLxPJB9VTGl0mUY7Ot6yg6YNY1RZUISJFzdwk/viewform?c=0&w=1
  
[10]
http://2018.code4lib.org/conduct/
  
[11]
http://2018.code4lib.org/conduct/#officers

**Comment by ranti** [comment]
Starting the draft document and shared it with Becky Yoose for comments and possible additional information.

**Comment by phette23** [comment]
We would need the link ready by mid- to late-November as that is when Concentra will build the registration form. I think giving ourselves a deadline of November 16th is reasonable.
