### ISSUE TITLE
Make the sponsor registration form easier to find

### ISSUE THREAD

**Issue by kaitlinnewson** [code4lib/2019.code4lib.org#49]
The sponsor registration form is currently buried at the bottom of the prospectus in the text. We need to make this stand out more, perhaps using a button or something similar.

**Comment by kaitlinnewson** [comment]
A button similar to the one on this page could work: https://2019.code4lib.org/general-info/propose-a-talk.html

**Comment by arosebrewer** [comment]
fixed via https://github.com/code4lib/2019.code4lib.org/pull/58
