### ISSUE TITLE
theme for 2019 update

### ISSUE THREAD

**Issue by phette23** [code4lib/2019.code4lib.org#7]
Proposal: Sharks colors https://teamcolorcodes.com/san-jose-sharks-color-codes/

**Comment by streeetlamp** [comment]
Personally big fan of the Sharks colors as it was my youth hockey team, obviously ties in with the location and is pretty nice looking anyway.

**Comment by phette23** [comment]
I thought we should hold it open at least until today's meeting in case someone objects or notices a poor text/bg contrast.
