### ISSUE TITLE
new testimonials

### ISSUE THREAD

**Issue by phette23** [code4lib/2019.code4lib.org#8]
We've had the same ones since the very first conference site I think. They're defined in _data/testimonials.yml

Ideas for getting new ones:

- search Twitter/social media for statements, ask for permission
- ask former keynotes or speakers
- ask former diversity scholarship recipients

**Comment by phette23** [comment]
Great. I'm waiting on one from Alyssa Loera and I know Justin said he received one from Mike Giarlo, so we're making good progress here.

**Comment by streeetlamp** [comment]
Kim responded and I have started a doc to keep them together. Let me know if anyone would like write access, you can currently comment.  
https://docs.google.com/document/d/1NA1YW-W1vMsjiVKDa0k7k1nZEvvI7Tghu62DzuGOqSI/edit?usp=sharing

**Comment by phette23** [comment]
I just realized that we linked to a Twitter handle for all the old testimonials. I don't think that should be a requirement so we may have to edit the index page a bit. I'll ask Alyssa if she wants her Twitter linked to or not.

**Comment by kaitlinnewson** [comment]
Aside from any obvious spelling/grammar mistakes, I don't think we should do much in terms of copy editing. Some might be too long though - should we set a max character or word length, then look at shortening those that don't meet it?

**Comment by metageeky** [comment]
Yes, you can just add more to the yml file and the randomized code will work. It's hard coded to six testimonials right now. There's no logic for to put short/long ones on different rows, so some sense of min/max word length is recommended.

**Comment by arosebrewer** [comment]
Current testimonials are all basically the length of a tweet (longest one is 203 characters, I think.) Should we say "tweet length" as our character limit (or at least "roughly")? If we do that, only two of these, I think, would qualify. And I'm happy to copy edit.

**Comment by streeetlamp** [comment]
I would say 300ish characters seem reasonable, @arosebrewer do you happen to have a list of the longer ones and contacts can reach out to ask for a slightly shorter version?

**Comment by streeetlamp** [comment]
color coded...so ashley of you.

**Comment by arosebrewer** [comment]
![i yam](https://user-images.githubusercontent.com/28605654/43869811-7c8bbb10-9b42-11e8-9c62-5e09a32c4010.jpg)

**Comment by arosebrewer** [comment]
Let's say 450 is the cap. 

**Whoever contacted the people with the quotes that have red characters limits, please reach back out to those people and ask them (nicely) to trim their quote OR ask if they feel comfortable having us edit/trim their quote for them**. 

https://docs.google.com/document/d/1NA1YW-W1vMsjiVKDa0k7k1nZEvvI7Tghu62DzuGOqSI/edit?usp=sharing

Those people are:
Francis Kayiwa
Laura Chuang
Nicky Andrews

**Comment by jcoyne** [comment]
I think this is looking a gift horse in the mouth. We've already asked a favor of these people and they've generously given their time and energy and now we're asking for more? 😠

**Comment by kaitlinnewson** [comment]
Perhaps a better approach would be to shorten it ourselves, then reach out to the contacts and make sure they're okay with it.

**Comment by jcoyne** [comment]
@kaitlinnewson that's a fantastic idea.

**Comment by arosebrewer** [comment]
I went in and made proposed edits to the 500+ character quotes. To limit the number of people we have to reach out to, I left anything under 500 characters alone. I also left Laura's quote alone because Laura is on this committee, right? Figured I'd let Laura take care of shortening her own quote. Comments and feedback welcome on the edits: https://docs.google.com/document/d/1NA1YW-W1vMsjiVKDa0k7k1nZEvvI7Tghu62DzuGOqSI/edit

**Comment by streeetlamp** [comment]
Thanks Ashley, I'm reaching out to those I have originally sent any requests that are over the limit. BIG THANKS FOR EDITING !

**Comment by streeetlamp** [comment]
I have pushed a branch https://github.com/code4lib/2019.code4lib.org/tree/issue%238edits where I have updated one testimonial so far to the edited version. Perhaps push any edited versions to that branch and we can merge together. 


![giphy](https://user-images.githubusercontent.com/1740634/44115693-8dde69c8-9fdc-11e8-804c-80aaf1b9dc1b.gif)

**Comment by snarkshow** [comment]
@arosebrewer I think I managed to get mine below 450 (assuming we are counting spaces?)

**Comment by kaitlinnewson** [comment]
Closing since we've gotten all edits up. Feel free to reopen if I've missed anything.
