### ISSUE TITLE
Speaker Photos

### ISSUE THREAD

**Issue by rtennant** [code4lib/2019.code4lib.org#94]
I'm uploading speaker photos to this folder as I receive them. Anyone with a link should be able to edit.

https://drive.google.com/drive/folders/1Fr7HyW81G8AMo0-mI03pNQPREQIVe8NQ?usp=sharing

**Comment by streeetlamp** [comment]
I just added a batch of what we have here so far to `assets/img/speakers` and I starred those images in Drive so any not starred should be new ones

**Comment by kaitlinnewson** [comment]
@streeetlamp it doesn't look like stars are shared across users - maybe a checklist could work, or we could move them into an 'added' folder (if that won't mess up anything else that's using the images).

**Comment by phette23** [comment]
+1 to an "added" folder

**Comment by phette23** [comment]
I guess we're not getting any more photos? @rtennant does that seem right?
