### ISSUE TITLE
workshop post content not recognized as markdown

### ISSUE THREAD

**Issue by phette23** [code4lib/2019.code4lib.org#99]
See #98 — workshop posts have frontmatter, use the "presentation" layout, and a body which is HTML right now. But in the presentation layout their HTML `{{content}}` isn't parsed as markdown—URLs that people helpfully pasted into their workshop descriptions aren't converted to links. I've tried changing the template to `{{ content | markdownify }}` but it didn't do anything.

**Comment by kaitlinnewson** [comment]
Could we save the workshop files as markdown instead?

**Comment by kaitlinnewson** [comment]
@phette23 Testing out saving these files as markdown and they seem to work the same - let me know if I can go ahead and submit a PR, or if there's a potential issue I'm missing.

**Comment by phette23** [comment]
They work the same as in the problem persists, or they're correctly interpreted as Markdown? Changing the file extensions to .md was something I'd considered but hadn't tried yet, I'd definitely look at a PR if it seems to work for you.

**Comment by phette23** [comment]
@kaitlinnewson I took a look at your workshops-markdown branch and it works! All the asterisk lists showing up as HTML lists is nice. I'm not sure if it's going to conflict badly with #101 where I touch a lot of the workshop posts, though.

Also, Luke's fromSheetsToJekyll tool that generates the Jekyll posts automatically wraps their content in a `<p>`. Not sure if we can/should keep that or not with the Markdown files. I could change the tool to emit .md files without wrapping paragraph tags.

**Comment by kaitlinnewson** [comment]
I think we can remove the <p> tags in the generated files, and just have them in the layout instead (I've added them to the presentations layout in my branch).

I'll take a look at #101 and see what I can do there.
